### ISSUE TITLE
Tracking: Localization

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#17]
```[tasklist]
### Tasks
- [x] Pull all copy out of hardcoded strings and from en_US JSON file
- [x] Update app to integrate with i18n framework and pull from expected file
- [x] Add locale selector to render all locales to choose from
- [x] Update dates/times in appropriate localized format
- [x] Sync with Storybook
- [x] Allow new locales to render out of the box from community contributed JSON files
```
