### ISSUE TITLE
Tracking: Update UI to match P0 Design specs

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-web#22]
Design spec: https://www.figma.com/file/8wFBRFdiYY0kOwLapSSiHA/In_box-Web-Designs-(Working)?node-id=973%3A8666&t=IjGQfErwGShxTEZf-1

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp-labs/xmtp-inbox-web/issues/44
- [ ] https://github.com/xmtp-labs/xmtp-inbox-web/issues/149
- [ ] https://github.com/xmtp-labs/xmtp-inbox-web/issues/150
```

**Comment by m-005** [comment]
@daria-github @bhavya2611 Let's do just one push for updating the UI of the features existing in xmtp.chat today. Let's make a separate push for the new features introduced in Darick's design [outlined here.](https://github.com/xmtp-labs/xmtp-inbox-web/issues/115) The second push of these new features can be a stretch goal for the end Q1 and the first push of a UI refresh of just xmtp.chat feature set satisfies our Q1 OKR

**Comment by daria-github** [comment]
Closing -- finished for current requirements, settings/gallery changes tracked in separate tickets.
