### ISSUE TITLE
Tracking : Going to Prod

### ISSUE THREAD

**Issue by bhavya2611** [xmtp-labs/xmtp-inbox-web#33]
Steps and checks to deploy this repo to production and archive older projects
### **PRE-RELEASE CHECKLIST — DAY BEFORE OR OF INTENDED RELEASE:**

**Core Eng Check** - Get the dev branch ready and stabilized for testing
- [x]  Bhavya or Daria to validate the following on dev branch — purpose is to validate everything is working as devs understand it should:
    - [x]  All automated tests passing (except ones we are aware are failing temporarily)
        - [x]  Test cases: [https://www.notion.so/xmtplabs/Example-App-Regression-Test-Suite-Plan-c4b53e63c6b94a42bef13ef5a1c61213](https://www.notion.so/Example-App-Regression-Test-Suite-Plan-c4b53e63c6b94a42bef13ef5a1c61213)
    - [x]  Manual spot-check for demo branch
    - [x]  Manual spot-check for non-demo branch, send at least 1 message
    - [x]  Manually check bug where not logged in and can still see modal pop-up even after having previously selected a provider

**Product/Design Check**
- [x]  Montez to validate the following on dev branch - purpose is to validate everything is working as product intends it to:
    - [x]  Manual spot-check for demo branch
    - [x]  Manual spot-check for non-demo branch, send at least 1 message
    - [x]  Manually check bug where not logged in and can still see modal pop-up even after having previously selected a provider

**3rd Party Eng Check**
- [x]  Elise to validate the following on dev branch - purpose is to validate cross-platform
    - [x]  Manual spot-check for demo branch
    - [x]  Manual spot-check for non-demo branch, send at least 1 message
    - [x]  Manually check bug where not logged in and can still see modal pop-up even after having previously selected a provider

### **RELEASE CHECKLIST:**

- [x] Merge `dev` —> `main`
- [x] Deploy demo, main, and dev on Vercel
> - demo - [https://vercel.com/xmtp-labs/xmtp-inbox-web-demo](https://vercel.com/xmtp-labs/xmtp-inbox-web-demo)
> - main - [https://vercel.com/xmtp-labs/xmtp-inbox-web](https://vercel.com/xmtp-labs/xmtp-inbox-web)
> - dev - [https://vercel.com/xmtp-labs/xmtp-inbox-web-dev](https://vercel.com/xmtp-labs/xmtp-inbox-web-dev)
- [x] Go through a round of bug bash and resolve issues found

### **POST-RELEASE — PPV (Post-Production Viewing — TO DO DURING RELEASE CALL):**

- [x]  Immediately after deployment, validate in production environment both demo and non-demo spot checks, to see if we need to revert anything (this may be excessive for now, but suggesting we err on the side of overly cautious about releases until we get things really stable, which will likely take a few weeks)
- [x]  One-time step needed for this next release: Per Bhavya, we’ll need some help to setup the domains on the new projects. 
- [x] The next step post that is make the xmtp-inbox-web ([https://github.com/xmtp-labs/xmtp-inbox-web](https://github.com/xmtp-labs/xmtp-inbox-web)) repo public, 
- [x] Change the links everywhere to point at this app 
- [x] If all goes well archive all the example-app projects
- [x] If all is good delete the vercel projects deployed from example-chat-react
